#+title: Exercise 1

[[http://neuralnetworksanddeeplearning.com/chap1.html#exercises_191892][link]]

* Sigmoid neurons simulating perceptrons, part I
Question:
Suppose we take all the weights and biases in a network of perceptrons, and
multiply them by a positive constant, $c>0$. Show that the behaviour of the
network doesn't change.

Solution:
The definition of a perceptron with bias is

\begin{eqnarray*}
  \mbox{output} = \left\{
    \begin{array}{ll}
      0 & \mbox{if } w\cdot x + b \leq 0 \\
      1 & \mbox{if } w\cdot x + b > 0
    \end{array}
  \right.
\tag{2}\end{eqnarray*}


multiplied with positive constant c gives us

\begin{eqnarray*}
  \mbox{output} = \left\{
    \begin{array}{ll}
      0 & \mbox{if } cw\cdot x + cb \leq 0 \\
      1 & \mbox{if } cw\cdot x + cb > 0
    \end{array}
  \right.
\tag{2}\end{eqnarray*}

\begin{eqnarray*}
  \mbox{output} = \left\{
    \begin{array}{ll}
      0 & \mbox{if } c(w\cdot x + b) \leq 0 \\
      1 & \mbox{if } c(w\cdot x + b) > 0
    \end{array}
  \right.
\tag{2}\end{eqnarray*}

\begin{eqnarray*}
  \mbox{output} = \left\{
    \begin{array}{ll}
      0 & \mbox{if } w\cdot x + b \leq 0 \\
      1 & \mbox{if } w\cdot x + b > 0
    \end{array}
  \right
\tag{2}\end{eqnarray*}

which does not change the behaviour of the network.

* Sigmoid neurons simulating perceptrons, part II
Question:
Suppose we have the same setup as the last problem - a network of perceptrons.
Suppose also that the overall input to the network of perceptrons has been
chosen. We won't need the actual input value, we just need the input to have
been fixed. Suppose the weights and biases are such that w⋅x+b≠0 for the input x
to any particular perceptron in the network. Now replace all the perceptrons in
the network by sigmoid neurons, and multiply the weights and biases by a
positive constant c>0. Show that in the limit as c→∞ the behaviour of this
network of sigmoid neurons is exactly the same as the network of perceptrons.
How can this fail when w⋅x+b=0 for one of the perceptrons?

Solution:
A sigmoid is defined by

\begin{eqnarray*}
  \sigma(z) \equiv \frac{1}{1+e^{-z}}
\end{eqnarray*}

so a sigmoid neuron becomes

\begin{eqnarray*}
  \frac{1}{1+\exp(-\sum_j w_j x_j-b)}
\end{eqnarray*}

Supposing the weights and biases are such that w⋅x+b≠0, multiplying them by a
positive constant c gives us

\begin{eqnarray*}
  \frac{1}{1+\exp(-\sum_j cw_j x_j-cb)}
\end{eqnarray*}

in the limit c→∞

\begin{align*}
  \lim_{c \to \infty} \frac{1}{1+\exp(-\sum_j cw_j x_j-cb)}
&= \lim_{c \to \infty} \frac{1}{1+\exp(-\sum_j c(w_j x_j-b)} \\
&= \lim_{c \to \infty} \frac{1}{1+\exp(-\sum_j c(w_j x_j-b)} \\
&= \left\{
    \begin{array}{ll}
      \lim_{c \to \infty} \frac{1}{1+\exp(\infty)} & \mbox{if } w\cdot x + b \leq 0 \\
      \lim_{c \to \infty} \frac{1}{1+\exp(-\infty)} & \mbox{if } w\cdot x + b > 0
    \end{array}
  \right \\
&= \left\{
    \begin{array}{ll}
      \frac{1}{1+\infty} & \mbox{if } w\cdot x + b \leq 0 \\
      \frac{1}{1+0} & \mbox{if } w\cdot x + b > 0
    \end{array}
  \right \\
&= \left\{
    \begin{array}{ll}
      0 & \mbox{if } w\cdot x + b \leq 0 \\
      1 & \mbox{if } w\cdot x + b > 0
    \end{array}
  \right \\
\end{align*}

this can fail when w⋅x+b=0 because

\begin{align*}
\frac{1}{1+\exp(0)} = \frac{1}{1+1} = \frac{1}{2}
\end{align*}
